import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "black",
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#FCD89E",
    textAlign: "center",
    marginBottom: 10,
    marginTop: 50,
  },
  descriptionMember: {
    color: "white",
    textAlign: "center",
    fontSize: 15,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  description: {
    color: "white",
    textAlign: "center",
    fontSize: 18,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 10,
    width: 290,
    textAlign: "left",
  },
  description2: {
    color: "#FCD89E",
    textAlign: "center",
    fontSize: 18,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 20,
    width: 290,
    textAlign: "left",
  },
  description3: {
    color: "#FCD89E",
    textAlign: "center",
    fontSize: 18,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 10,
    width: 290,
    textAlign: "left",
  },
  description4: {
    color: "black",
    textAlign: "left",
    fontSize: 25,
    top: -210,
    right: 78,
    fontWeight: "bold",
  },
  description5: {
    color: "black",
    textAlign: "left",
    fontSize: 14,
    position: "absolute",
    top: 422,
    left: 20,
    zIndex: 1,
    width: 240,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  description6: {
    color: "#FCD89E",
    textAlign: "left",
    fontSize: 25,
    top: -60,
    fontWeight: "bold",
  },
  image: {
    borderRadius: 100,
    width: 150,
    height: 150,
    marginBottom: 10,
  },
  imagedois: {
    top: -200,
    left: 120,
  },
  imagebranca: {
    alignSelf: "center",
    width: 780,
    height: 300,
    top: 25,
    left: 0,
    right: 0,
    bottom: 0,
  },
  memberName: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
    textAlign: "center",
  },
  slide: {
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    width: 220,
    height: 350,
    marginHorizontal: 5,
    marginVertical: 0,
    borderColor: "#FCD89E",
    borderWidth: 2,
    marginBottom: 50,
  },
});

export default styles;
